language: java
sudo: required
install: /bin/true

jdk:
- oraclejdk8

before_install:
- gradle wrapper
- sudo apt-get install jq

before_script:
    - wget https://services.gradle.org/distributions/gradle-2.14-bin.zip
    - unzip gradle-2.14-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.14
    - export PATH=$GRADLE_HOME/bin:$PATH

script:
- ./gradlew assemble
- ./gradlew check
- ./gradlew codeCoverageReport
